# Generated by Django 3.2 on 2021-04-25 00:00

from django.db import migrations, models
import django.db.models.deletion
import photographs.utils.media_storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('cover_photo', models.ImageField(upload_to=photographs.utils.media_storage.store_album_image)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='photo')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photographs.album')),
            ],
        ),
    ]
